prodDataBuilder:
  target: prod
  outputs:
    dev:
      type: postgres
      host: "locahost"
      user: "root"
      password: "2skj(Hk2hksf2"
      port: 5432
      dbname: "analytics"
      schema: ""   # <- destino padrão (transformações)
      threads: 4
      keepalives_idle: 0

    prod:
      type: postgres
      host: "localhost"
      user: "root"
      password: "2skj(Hk2hksf2"
      port: 5432
      dbname: "analytics"
      schema: ''  # <- idem
      threads: 8
